### PR TITLE
Reworking punctuation and target ref with tests

### PR DESCRIPTION
**Pull request by dandehavilland**

### CODE REVIEW

**Comment by dstaley** [comment]
@dandehavilland It looks like you're generating a unique ID attribute if the element provided to target doesn't have one set. Does the library rely internally on the element having an ID set? If not, is it feasible to just maintain a reference to the actual element as opposed to giving it a new ID?

**Comment by dandehavilland** [comment]
There's no internal requirement for an ID, but I'd prefer to have the element identify itself rather than keeping a reference. How about storing that unique ref as `data-mg` instead?

**Comment by dstaley** [comment]
I think that's a better approach since modifying the ID attribute might cause issues with other libraries that use it to identify elements (such as data binding libraries). Are there any issues that using a data attribute might cause that you can think of?

**Comment by dandehavilland** [comment]
I don't think so, but just to be safe, I'm now scoping the data attribute by `mg-` rather than straight-up naming it `mg`.

**Comment by dstaley** [comment]
Should the tests be passing? I'm getting failures on just about every test.

**Comment by dandehavilland** [comment]
Yes indeed - that's now fixed.

**Comment by dstaley** [comment]
Awesome, looks like all the tests are passing (including my original test from switching between a missing chart and line chart). Merging in and updating the original PR.

**Pull request merged**
